title: Doug Rose # your name (or website title) here
logo: "/images/profile_pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a driven data analyst, actively pursuing opportunities to elevate my skills and bring meaningful contributions to an organization by uncovering the compelling stories hidden within the data. 
  <br><br>
  SQL | R | Excel | Tableau 
  <br><br>
  <a href="https://www.linkedin.com/in/doug-rose-3b2382234/">LinkedIn Profile</a>
  <br><br>
  <a href="https://github.com/drose1988">Github Profile</a>
  
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
